repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.9.10
  hooks:
    # Run the linter.
    - id: ruff
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format
#- repo: local
#  hooks:
#    - id: pytest
#      name: pytest
#      entry: uv run pytest --cov
#      language: system
#      types: [python]
#      pass_filenames: false
#      always_run: true
#      stages: [pre-commit]
